views: "/opt/khaospy/www-dancer-tt/"

plugins:
    Database:
        driver: Pg
        database: 'khaospy'
        host: 'localhost'
        port: 5432
        username: 'khaospy_write'
        password: 'password'
        connection_check_threshold: 10
