views: "/opt/khaospy/www-dancer-tt/"

session: Memcached
engines:
  session:
    Memcached:
      memcached_servers: "127.0.0.1:11211"

#
#plugins:
#    Database:
#        driver: Pg
#        database: 'khaospy'
#        host: 'localhost'
#        port: 5432
#        sslmode : 'require'
#        username: 'khaospy_write'
#        password: 'password'
#        connection_check_threshold: 10
#        dbi_params:
#            sslmode: 'require'


